language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install build-essential binutils libproj-dev libgdal-dev python-gdal
  - sudo apt-get install postgresql-10-postgis-2.4
  - pip install pipenv
  - pipenv install

addons:
  apt:
    packages:
      - postgresql-10-postgis-2.4
  postgresql: '10'
services:
  - postgresql

script:
  - pytest